# go语言错误
- error类型是一个接口类型，这是它的定义：
```go
type error interface { 
    Error() string 
}
```

## if err!=nil
- 函数调用时判断返回值

## errors.New 创建error
```go
package main

import (
	"errors"
	"log"
	"strings"
)

func validate(name string) (ok bool, err error) {
	if !strings.HasPrefix(name, "mysql") {
		return false, errors.New("name must start with mysql")
	}
	return true, nil
}

func main() {
	s1 := "mysql-abc"
	s2 := "redis-abc"
	_, err := validate(s1)
	if err != nil {
		log.Printf("[judge1][validate][err:%v]", err)
	}
	if ok, err := validate(s2); err != nil {
		log.Printf("[judge2][validate][err:%v][ok:%v]", err, ok)
	}
}

/*
2021/08/30 23:22:16 [judge2][validate][err:name must start with mysql][ok:false]
*/
```


## 复杂的错误类型
- 以os包举例 提供了 LinkError、PathError、SyscallError 
- 这些实现了 error 接口的错误类型，以 PathError 为例，顾名思义，它主要用于表示路径相关的错误信息，比如文件不存在，其底层类型结构信息如下：
```go
func (e *PathError) Error() string { 
    return e.Op + " " + e.Path + ": " + e.Err.Error() 
}
```
- 样例
```go
package main

import (
	"log"
	"os"
)

// 以os包举例 提供了 LinkError、PathError、SyscallError 
func main() {

	f1, err := os.Stat("test.txt")
	if err != nil {
		switch err.(type) {
		case *os.PathError:
			log.Printf("PathError")
		case *os.LinkError:
			log.Printf("LinkError")
		case *os.SyscallError:
			log.Printf("SyscallError")
		}
	} else {
		log.Printf("f1:%v", f1)
	}
}

/*
2021/08/30 23:41:19 PathError
*/
```


## 自定义error
- 使用结构体额外的msg字段扩展
- 自定义自己的struct，添加用于存储我们需要额外信息的字段
- `缺点就是定义很多结构体`
```go
package main

import (
	"errors"
	"fmt"
)

type MyError struct {
	abc error
	msg string
}

func (e *MyError) Error() string {
	return e.abc.Error() + e.msg
}

func main() {

	err := errors.New("原始错误")
	myErr := MyError{
		err: err,
		msg: " 数据上传问题",
	}
	fmt.Println(myErr.Error())
}

/*
2021/08/30 23:50:09 原始错误自定义错误

Error()源码
// The error built-in interface type is the conventional interface for
// representing an error condition, with the nil value representing no error.
type error interface {
	Error() string
}
*/
```

## golang 1.13中的Error Wrapping 错误嵌套
- 用来给错误添加额外信息的信息
- Golang并没有提供什么Wrap函数，而是`扩展了fmt.Errorf函数`，加了一个%w来生成一个可以Wrapping Error
```go
package main

import (
	"errors"
	"fmt"
)

func main() {

	err := errors.New("原始错误")
	myErr := fmt.Errorf("自定义错误:%w", err)
	fmt.Println(myErr)
}

/*
自定义错误:原始错误
*/
```